config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  enum genre: {"文芸": 1, "人文": 2, "実用書": 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

     def configure_permitted_parameters
       #以下の:name部分は追加したカラム名に変える
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create!(create_params)
    render :index
  end

  private
  def create_params
    params.require(:book).permit(:title, :author, :publisher, :price, :genre, :keyword, :summary, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class="top-contain">
  <div class="index">
    <div class="book 1">
      <div class="book__image">
      </div>
      <div class="book__info">
        <div class="title">
          qqqqq
        </div>
        <div class="author">
          QQQ
        </div>
      </div>
    </div>
    <div class="book 2">
      <div class="book__image">
      </div>
      <div class="book__title">
        title
      </div>
    </div>
    <div class="book 3">
      <div class="book__image">
      </div>
      <div class="book__title">
        eeeeee
      </div>
    </div>
    <div class="book 4">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 5">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 6">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 7">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 8">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 9">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 10">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 11">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 12">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 13">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 14">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
    <div class="book 15">
      <div class="book__image">
      </div>
      <div class="book__title">
      </div>
    </div>
  </div>
</div>

<div class="hidden-contents" >
  <ul class="link-to">
    <li><%= link_to "本を登録", new_book_path %></li>
    <% if user_signed_in? %>
    <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "sign in", new_user_session_path %></li>
    <% end %>
</div>

app/views/books/new.html.erb
<div class="register-book">
  <h2 class="register-book__title">Register BOOK</h2>
  <div class="registration-forms">
    <div class="registration-forms__image form">
      <h3>IMAGE</h3>
      <%= form_for @book do |f| %>
        <div class="fallback dz-message needsclick">
          <%= f.file_field :image, html: {class:'dropzone', id: "item-dropzone"}%>
        </div>
        <div class="registration-forms__title form">
          <h3>TITLE</h3>
          <%= f.text_field :title, placeholder: "本のタイトル" %>
        </div>
        <div class="registration-forms__author form">
          <h3>AUTHOR</h3>
          <%= f.text_field :author, placeholder: "著者" %>
        </div>
        <div class="registration-forms__publisher form">
          <h3>PUBLISHER</h3>
          <%= f.text_field :publisher, placeholder: "出版社" %>
        </div>
        <div class="ragistration-forms__price form">
          <h3>PRICE</h3>
          <%= f.text_field :price, placeholder: "値段" %>
        </div>
        <div class="registration-forms__genre form">
          <h3>JENRE</h3>
          <%= f.select :genre, Book.genres.keys %>
        </div>
        <div class="registration-forms__kleyword form">
          <h3>KEYWORD</h3>
          <%= f.text_field :keyword, placeholder: "キーワード" %>
        </div>
        <div class="registration-forms__summary form">
          <h3>SUMMSRY</h3>
          <%= f.text_area :summary, placeholder: "要約" %>
        </div>
        <%= f.submit "登録する" %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBookLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header clearfix">
      <h1 class="user_name">
        USERさんのBOOK LOG
      </h1>
      <ulf class="container">
        <li class="container__user"></li>
        <li class="container__home"><i class="fa fa-home"></i></li>
        <li class="container__dropdown"><i class="fa fa-align-justify"></i></li>
      </ul>
    </header>
    <div class="background">
      <%= yield %>
    </div>
    <footer class="footer">
    </footer>
  </body>
</html>